### ISSUE TITLE
soundness problem?

### ISSUE THREAD

**Issue by etiennebirling** [herbie-fp/rival#8]
Hello,
I am currently stuck on a result I considered as a bug, but I wanted to know whether it was actually intentional, or not.
How to reproduce the behavior (racket 8.3).
**racket
(require  rival math/bigfloat)
(ival-pow (ival +nan.bf (bf 1)) (ival (bf 0) +nan.bf) )**
>(ival (bf 1) (bf 1))

In my understanding, a binary operator receiving an interval allowing NaN should return an interval that would also allow NaN, is that correct? 
What interpretation would make this result correct otherwise?

**Comment by pavpanchekha** [comment]
Hmm, what version of Rival are you running? You might need to update (use `raco pkg update rival`).

What's going on here relates to how NaN is treated by Rival. Since NaN is not a real number, it's considered an error value. Therefore the interval from `+nan.bf` to `1.bf` is an "illegal interval". You can check this by calling `(ival-error? ...)`. That should return `(ival #t #t)` meaning that the interval both can and must be illegal. In recent versions of Rival, this means your actual interval should print as `ival-illegal`, but it seems not to be doing that.

In any case, an illegal interval just represents an error; it doesn't contain any real numbers, and its endpoints are meaningless. (You can think of it as "only containing `+nan.bf`", if you like.)

**Comment by etiennebirling** [comment]
many thanks, I just had an old version installed
